name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      ECR_REGISTRY_URL: 676933797202.dkr.ecr.us-east-1.amazonaws.com/docker-project
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        id: login-ecr
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY_URL/docker-project
      
      - name: Build Docker image
        run: docker build -t exercise-app .

      - name: Tag Docker image
        run: docker tag excercise-app $ECR_REGISTRY_URL/excercise-app

      - name: Push Docker image to ECR
        run: docker push $ECR_REGISTRY_URL/excercise-app:latest